"""CMR document generation."""

from html import escape

from app.companies.models import Company
from app.customers.models import Customer
from app.orders.models import Order


def build_cmr_html(*, company: Company, customer: Customer, order: Order) -> str:
    """Build a printable CMR HTML document for an order."""
    vehicle_rows = "".join(
        (
            "<tr>"
            f"<td>{escape(vehicle.make or '')}</td>"
            f"<td>{escape(vehicle.model or '')}</td>"
            f"<td>{escape(vehicle.vin or '')}</td>"
            "</tr>"
        )
        for vehicle in order.vehicles
        if vehicle.deleted_at is None
    )
    stop_rows = "".join(
        (
            "<tr>"
            f"<td>{escape(stop.stop_type)}</td>"
            f"<td>{escape(stop.city or stop.address or '')}</td>"
            f"<td>{escape(stop.company_name or '')}</td>"
            "</tr>"
        )
        for stop in order.stops
        if stop.deleted_at is None
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>CMR {escape(order.order_number)}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 32px; color: #1b3a5f; }}
    h1 {{ margin-bottom: 8px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
    th, td {{ border: 1px solid #ccc; padding: 8px; text-align: left; }}
    th {{ background: #e8eef4; }}
  </style>
</head>
<body>
  <h1>CMR Consignment Note</h1>
  <p><strong>Order:</strong> {escape(order.order_number)}</p>
  <p><strong>Carrier:</strong> {escape(company.name)}</p>
  <p><strong>Customer:</strong> {escape(customer.company_name)}</p>
  <p><strong>Status:</strong> {escape(order.status)}</p>
  <h2>Stops</h2>
  <table>
    <thead><tr><th>Type</th><th>Location</th><th>Company</th></tr></thead>
    <tbody>{stop_rows or '<tr><td colspan="3">No stops recorded</td></tr>'}</tbody>
  </table>
  <h2>Vehicles</h2>
  <table>
    <thead><tr><th>Make</th><th>Model</th><th>VIN</th></tr></thead>
    <tbody>{vehicle_rows or '<tr><td colspan="3">No vehicles recorded</td></tr>'}</tbody>
  </table>
  <p>Generated by ProDrive. Print this document for transport use.</p>
</body>
</html>
"""
